module.exports = {
  TYPE_PK: 'pk',
  TYPE_UPK: 'upk',
  TYPE_BIGPK: 'bigpk',
  TYPE_UBIGPK: 'ubigpk',
  TYPE_CHAR: 'char',
  TYPE_STRING: 'string',
  TYPE_TEXT: 'text',
  TYPE_TINYINT: 'tinyint',
  TYPE_SMALLINT: 'smallint',
  TYPE_INTEGER: 'integer',
  TYPE_BIGINT: 'bigint',
  TYPE_FLOAT: 'float',
  TYPE_DOUBLE: 'double',
  TYPE_DECIMAL: 'decimal',
  TYPE_DATETIME: 'datetime',
  TYPE_TIMESTAMP: 'timestamp',
  TYPE_TIME: 'time',
  TYPE_DATE: 'date',
  TYPE_BINARY: 'binary',
  TYPE_BOOLEAN: 'boolean',
  TYPE_MONEY: 'money',
  TYPE_JSON: 'json',
};